# supported versions here: https://hub.docker.com/_/rust
ARG RUST_BUILDER_VERSION=slim-bookworm

########################
## builder image
########################
FROM ghcr.io/rust-cross/rust-musl-cross:x86_64-musl AS builder

RUN apt-get update \
    && apt-get -y install git cmake perl pkg-config libclang-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup toolchain install 1.98 --profile minimal --no-self-update --target x86_64-unknown-linux-musl && rustup default 1.98

WORKDIR /redlib

# download (most) dependencies in their own layer
COPY Cargo.lock Cargo.toml ./
RUN mkdir src && echo "fn main() { panic!(\"why am i running?\") }" > src/main.rs
RUN cargo build --release --locked --bin redlib --target x86_64-unknown-linux-musl
RUN rm ./src/main.rs && rmdir ./src

# copy the source and build the redlib binary
COPY . ./
RUN cargo build --release --locked --bin redlib --target x86_64-unknown-linux-musl
RUN echo "finished building redlib!"

########################
## release image
########################
FROM gcr.io/distroless/static:nonroot AS release

COPY --from=builder /redlib/target/x86_64-unknown-linux-musl/release/redlib /usr/local/bin/redlib

EXPOSE 8080

LABEL org.opencontainers.image.authors="sigaloid"

CMD ["redlib"]
